### ISSUE TITLE
Copyright notice

### ISSUE THREAD

**Issue by mtrojnar** [josealf/stunnel-win32#1]
Nice work!

Please also publish the actual copyright notice (https://github.com/mtrojnar/stunnel/blob/master/COPYING.md), and not only the generic text of GPLv2.

**Comment by josealf** [comment]
Hi Michal,
Thank you. I just added the COPYING.md file. I think I should also add the COPYRIGHT.md file that is referenced in the text, although the it's just the GPL license text. Do you agree?


    On Thursday, March 5, 2020, 03:11:16 AM GMT-5, Michał Trojnara <notifications@github.com> wrote:  
 
 
Nice work!

Please also publish the actual copyright notice (https://github.com/mtrojnar/stunnel/blob/master/COPYING.md), and not only the generic text of GPLv2.

**Comment by mtrojnar** [comment]
I agree.
